// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/model.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OllamaAvailable  bool                   `protobuf:"varint,1,opt,name=ollama_available,json=ollamaAvailable,proto3" json:"ollama_available,omitempty"`
	OllamaVersion    string                 `protobuf:"bytes,2,opt,name=ollama_version,json=ollamaVersion,proto3" json:"ollama_version,omitempty"`
	ModelsLoaded     int32                  `protobuf:"varint,3,opt,name=models_loaded,json=modelsLoaded,proto3" json:"models_loaded,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,5,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	GpuDevices       []string               `protobuf:"bytes,6,rep,name=gpu_devices,json=gpuDevices,proto3" json:"gpu_devices,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOllamaAvailable() bool {
	if x != nil {
		return x.OllamaAvailable
	}
	return false
}

func (x *HealthResponse) GetOllamaVersion() string {
	if x != nil {
		return x.OllamaVersion
	}
	return ""
}

func (x *HealthResponse) GetModelsLoaded() int32 {
	if x != nil {
		return x.ModelsLoaded
	}
	return 0
}

func (x *HealthResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *HealthResponse) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *HealthResponse) GetGpuDevices() []string {
	if x != nil {
		return x.GpuDevices
	}
	return nil
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ListModelsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDetails bool                   `protobuf:"varint,1,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_api_proto_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsRequest) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

type ModelInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelFamily    string                 `protobuf:"bytes,2,opt,name=model_family,json=modelFamily,proto3" json:"model_family,omitempty"`
	ParameterCount int64                  `protobuf:"varint,3,opt,name=parameter_count,json=parameterCount,proto3" json:"parameter_count,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Quantization   string                 `protobuf:"bytes,5,opt,name=quantization,proto3" json:"quantization,omitempty"`
	ContextLength  int32                  `protobuf:"varint,6,opt,name=context_length,json=contextLength,proto3" json:"context_length,omitempty"`
	IsLoaded       bool                   `protobuf:"varint,7,opt,name=is_loaded,json=isLoaded,proto3" json:"is_loaded,omitempty"`
	LastUsed       int64                  `protobuf:"varint,8,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_api_proto_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{3}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetModelFamily() string {
	if x != nil {
		return x.ModelFamily
	}
	return ""
}

func (x *ModelInfo) GetParameterCount() int64 {
	if x != nil {
		return x.ParameterCount
	}
	return 0
}

func (x *ModelInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModelInfo) GetQuantization() string {
	if x != nil {
		return x.Quantization
	}
	return ""
}

func (x *ModelInfo) GetContextLength() int32 {
	if x != nil {
		return x.ContextLength
	}
	return 0
}

func (x *ModelInfo) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

func (x *ModelInfo) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_api_proto_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{4}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type PreloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelName      string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	KeepAlive      bool                   `protobuf:"varint,2,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"` // Keep model in memory
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreloadRequest) Reset() {
	*x = PreloadRequest{}
	mi := &file_api_proto_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadRequest) ProtoMessage() {}

func (x *PreloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadRequest.ProtoReflect.Descriptor instead.
func (*PreloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{5}
}

func (x *PreloadRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *PreloadRequest) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *PreloadRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type PreloadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LoadTimeMs      float64                `protobuf:"fixed64,2,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreloadResponse) Reset() {
	*x = PreloadResponse{}
	mi := &file_api_proto_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadResponse) ProtoMessage() {}

func (x *PreloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadResponse.ProtoReflect.Descriptor instead.
func (*PreloadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{6}
}

func (x *PreloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreloadResponse) GetLoadTimeMs() float64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

func (x *PreloadResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *PreloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ModelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStatusRequest) Reset() {
	*x = ModelStatusRequest{}
	mi := &file_api_proto_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStatusRequest) ProtoMessage() {}

func (x *ModelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStatusRequest.ProtoReflect.Descriptor instead.
func (*ModelStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{7}
}

func (x *ModelStatusRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type ModelStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelName       string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "loaded", "loading", "unloaded", "error"
	MemoryUsedBytes int64                  `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	LastUsed        int64                  `protobuf:"varint,4,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	InferenceCount  int32                  `protobuf:"varint,5,opt,name=inference_count,json=inferenceCount,proto3" json:"inference_count,omitempty"`
	AvgLatencyMs    float64                `protobuf:"fixed64,6,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelStatusResponse) Reset() {
	*x = ModelStatusResponse{}
	mi := &file_api_proto_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStatusResponse) ProtoMessage() {}

func (x *ModelStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStatusResponse.ProtoReflect.Descriptor instead.
func (*ModelStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{8}
}

func (x *ModelStatusResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelStatusResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ModelStatusResponse) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *ModelStatusResponse) GetInferenceCount() int32 {
	if x != nil {
		return x.InferenceCount
	}
	return 0
}

func (x *ModelStatusResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

type WatchStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelNames      []string               `protobuf:"bytes,1,rep,name=model_names,json=modelNames,proto3" json:"model_names,omitempty"`                 // Empty = watch all
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // Update interval (default: 10)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_api_proto_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{9}
}

func (x *WatchStatusRequest) GetModelNames() []string {
	if x != nil {
		return x.ModelNames
	}
	return nil
}

func (x *WatchStatusRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "loaded", "unloaded", "error", "inference"
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_api_proto_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_model_proto_rawDescGZIP(), []int{10}
}

func (x *StatusEvent) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StatusEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StatusEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *StatusEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_model_proto protoreflect.FileDescriptor

const file_api_proto_model_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/model.proto\x12\x0fcortex.model.v1\"\x0f\n" +
	"\rHealthRequest\"\xa9\x02\n" +
	"\x0eHealthResponse\x12)\n" +
	"\x10ollama_available\x18\x01 \x01(\bR\x0follamaAvailable\x12%\n" +
	"\x0eollama_version\x18\x02 \x01(\tR\rollamaVersion\x12#\n" +
	"\rmodels_loaded\x18\x03 \x01(\x05R\fmodelsLoaded\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x05 \x01(\x03R\x10memoryTotalBytes\x12\x1f\n" +
	"\vgpu_devices\x18\x06 \x03(\tR\n" +
	"gpuDevices\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\"<\n" +
	"\x11ListModelsRequest\x12'\n" +
	"\x0finclude_details\x18\x01 \x01(\bR\x0eincludeDetails\"\x8f\x02\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fmodel_family\x18\x02 \x01(\tR\vmodelFamily\x12'\n" +
	"\x0fparameter_count\x18\x03 \x01(\x03R\x0eparameterCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\"\n" +
	"\fquantization\x18\x05 \x01(\tR\fquantization\x12%\n" +
	"\x0econtext_length\x18\x06 \x01(\x05R\rcontextLength\x12\x1b\n" +
	"\tis_loaded\x18\a \x01(\bR\bisLoaded\x12\x1b\n" +
	"\tlast_used\x18\b \x01(\x03R\blastUsed\"H\n" +
	"\x12ListModelsResponse\x122\n" +
	"\x06models\x18\x01 \x03(\v2\x1a.cortex.model.v1.ModelInfoR\x06models\"w\n" +
	"\x0ePreloadRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x02 \x01(\bR\tkeepAlive\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\x8f\x01\n" +
	"\x0fPreloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\fload_time_ms\x18\x02 \x01(\x01R\n" +
	"loadTimeMs\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"3\n" +
	"\x12ModelStatusRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"\xe4\x01\n" +
	"\x13ModelStatusResponse\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12\x1b\n" +
	"\tlast_used\x18\x04 \x01(\x03R\blastUsed\x12'\n" +
	"\x0finference_count\x18\x05 \x01(\x05R\x0einferenceCount\x12$\n" +
	"\x0eavg_latency_ms\x18\x06 \x01(\x01R\favgLatencyMs\"`\n" +
	"\x12WatchStatusRequest\x12\x1f\n" +
	"\vmodel_names\x18\x01 \x03(\tR\n" +
	"modelNames\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"\x83\x01\n" +
	"\vStatusEvent\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xb7\x03\n" +
	"\fModelService\x12L\n" +
	"\tGetHealth\x12\x1e.cortex.model.v1.HealthRequest\x1a\x1f.cortex.model.v1.HealthResponse\x12U\n" +
	"\n" +
	"ListModels\x12\".cortex.model.v1.ListModelsRequest\x1a#.cortex.model.v1.ListModelsResponse\x12Q\n" +
	"\fPreloadModel\x12\x1f.cortex.model.v1.PreloadRequest\x1a .cortex.model.v1.PreloadResponse\x12[\n" +
	"\x0eGetModelStatus\x12#.cortex.model.v1.ModelStatusRequest\x1a$.cortex.model.v1.ModelStatusResponse\x12R\n" +
	"\vWatchStatus\x12#.cortex.model.v1.WatchStatusRequest\x1a\x1c.cortex.model.v1.StatusEvent0\x01B5Z3github.com/cortex/cortex-services/api/proto/modelpbb\x06proto3"

var (
	file_api_proto_model_proto_rawDescOnce sync.Once
	file_api_proto_model_proto_rawDescData []byte
)

func file_api_proto_model_proto_rawDescGZIP() []byte {
	file_api_proto_model_proto_rawDescOnce.Do(func() {
		file_api_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_model_proto_rawDesc), len(file_api_proto_model_proto_rawDesc)))
	})
	return file_api_proto_model_proto_rawDescData
}

var file_api_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_model_proto_goTypes = []any{
	(*HealthRequest)(nil),       // 0: cortex.model.v1.HealthRequest
	(*HealthResponse)(nil),      // 1: cortex.model.v1.HealthResponse
	(*ListModelsRequest)(nil),   // 2: cortex.model.v1.ListModelsRequest
	(*ModelInfo)(nil),           // 3: cortex.model.v1.ModelInfo
	(*ListModelsResponse)(nil),  // 4: cortex.model.v1.ListModelsResponse
	(*PreloadRequest)(nil),      // 5: cortex.model.v1.PreloadRequest
	(*PreloadResponse)(nil),     // 6: cortex.model.v1.PreloadResponse
	(*ModelStatusRequest)(nil),  // 7: cortex.model.v1.ModelStatusRequest
	(*ModelStatusResponse)(nil), // 8: cortex.model.v1.ModelStatusResponse
	(*WatchStatusRequest)(nil),  // 9: cortex.model.v1.WatchStatusRequest
	(*StatusEvent)(nil),         // 10: cortex.model.v1.StatusEvent
}
var file_api_proto_model_proto_depIdxs = []int32{
	3,  // 0: cortex.model.v1.ListModelsResponse.models:type_name -> cortex.model.v1.ModelInfo
	0,  // 1: cortex.model.v1.ModelService.GetHealth:input_type -> cortex.model.v1.HealthRequest
	2,  // 2: cortex.model.v1.ModelService.ListModels:input_type -> cortex.model.v1.ListModelsRequest
	5,  // 3: cortex.model.v1.ModelService.PreloadModel:input_type -> cortex.model.v1.PreloadRequest
	7,  // 4: cortex.model.v1.ModelService.GetModelStatus:input_type -> cortex.model.v1.ModelStatusRequest
	9,  // 5: cortex.model.v1.ModelService.WatchStatus:input_type -> cortex.model.v1.WatchStatusRequest
	1,  // 6: cortex.model.v1.ModelService.GetHealth:output_type -> cortex.model.v1.HealthResponse
	4,  // 7: cortex.model.v1.ModelService.ListModels:output_type -> cortex.model.v1.ListModelsResponse
	6,  // 8: cortex.model.v1.ModelService.PreloadModel:output_type -> cortex.model.v1.PreloadResponse
	8,  // 9: cortex.model.v1.ModelService.GetModelStatus:output_type -> cortex.model.v1.ModelStatusResponse
	10, // 10: cortex.model.v1.ModelService.WatchStatus:output_type -> cortex.model.v1.StatusEvent
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_model_proto_init() }
func file_api_proto_model_proto_init() {
	if File_api_proto_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_model_proto_rawDesc), len(file_api_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_model_proto_goTypes,
		DependencyIndexes: file_api_proto_model_proto_depIdxs,
		MessageInfos:      file_api_proto_model_proto_msgTypes,
	}.Build()
	File_api_proto_model_proto = out.File
	file_api_proto_model_proto_goTypes = nil
	file_api_proto_model_proto_depIdxs = nil
}
