// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/cache.proto

package cachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A cached file entry.
type CacheEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mtime         int64                  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ContentHash   string                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	AccessedAt    int64                  `protobuf:"varint,6,opt,name=accessed_at,json=accessedAt,proto3" json:"accessed_at,omitempty"`
	HitCount      int32                  `protobuf:"varint,7,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_api_proto_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CacheEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CacheEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *CacheEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CacheEntry) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *CacheEntry) GetAccessedAt() int64 {
	if x != nil {
		return x.AccessedAt
	}
	return 0
}

func (x *CacheEntry) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValidateMtime bool                   `protobuf:"varint,2,opt,name=validate_mtime,json=validateMtime,proto3" json:"validate_mtime,omitempty"` // Check if file has been modified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetRequest) GetValidateMtime() bool {
	if x != nil {
		return x.ValidateMtime
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Entry         *CacheEntry            `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	Stale         bool                   `protobuf:"varint,3,opt,name=stale,proto3" json:"stale,omitempty"` // True if mtime changed since caching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetEntry() *CacheEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *GetResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mtime         int64                  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = use default TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SetRequest) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *SetRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SetRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Evicted       bool                   `protobuf:"varint,2,opt,name=evicted,proto3" json:"evicted,omitempty"` // True if another entry was evicted to make room
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{4}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetEvicted() bool {
	if x != nil {
		return x.Evicted
	}
	return false
}

func (x *SetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{6}
}

func (x *InvalidateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	ValidateMtime bool                   `protobuf:"varint,2,opt,name=validate_mtime,json=validateMtime,proto3" json:"validate_mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *BatchGetRequest) GetValidateMtime() bool {
	if x != nil {
		return x.ValidateMtime
	}
	return false
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]*CacheEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Misses        []string               `protobuf:"bytes,2,rep,name=misses,proto3" json:"misses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetResponse) GetEntries() map[string]*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BatchGetResponse) GetMisses() []string {
	if x != nil {
		return x.Misses
	}
	return nil
}

type BatchSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SetRequest          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetRequest) Reset() {
	*x = BatchSetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRequest) ProtoMessage() {}

func (x *BatchSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRequest.ProtoReflect.Descriptor instead.
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{9}
}

func (x *BatchSetRequest) GetEntries() []*SetRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetResponse) Reset() {
	*x = BatchSetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetResponse) ProtoMessage() {}

func (x *BatchSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetResponse.ProtoReflect.Descriptor instead.
func (*BatchSetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{10}
}

func (x *BatchSetResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchSetResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BatchSetResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{11}
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries   int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,2,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	MaxEntries     int64                  `protobuf:"varint,3,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	MaxSizeBytes   int64                  `protobuf:"varint,4,opt,name=max_size_bytes,json=maxSizeBytes,proto3" json:"max_size_bytes,omitempty"`
	Hits           int64                  `protobuf:"varint,5,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses         int64                  `protobuf:"varint,6,opt,name=misses,proto3" json:"misses,omitempty"`
	Evictions      int64                  `protobuf:"varint,7,opt,name=evictions,proto3" json:"evictions,omitempty"`
	HitRate        float64                `protobuf:"fixed64,8,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *StatsResponse) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetMaxEntries() int64 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *StatsResponse) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.MaxSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *StatsResponse) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *StatsResponse) GetEvictions() int64 {
	if x != nil {
		return x.Evictions
	}
	return 0
}

func (x *StatsResponse) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *StatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PreCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patterns      []string               `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`                  // Glob patterns (e.g., "*.py")
	Directory     string                 `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`                // Root directory
	MaxFiles      int32                  `protobuf:"varint,3,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"` // Max files to cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCacheRequest) Reset() {
	*x = PreCacheRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCacheRequest) ProtoMessage() {}

func (x *PreCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCacheRequest.ProtoReflect.Descriptor instead.
func (*PreCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{13}
}

func (x *PreCacheRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *PreCacheRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *PreCacheRequest) GetMaxFiles() int32 {
	if x != nil {
		return x.MaxFiles
	}
	return 0
}

type PreCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cached        int32                  `protobuf:"varint,1,opt,name=cached,proto3" json:"cached,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	Files         []string               `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCacheResponse) Reset() {
	*x = PreCacheResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCacheResponse) ProtoMessage() {}

func (x *PreCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCacheResponse.ProtoReflect.Descriptor instead.
func (*PreCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{14}
}

func (x *PreCacheResponse) GetCached() int32 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *PreCacheResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *PreCacheResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *PreCacheResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{15}
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       int32                  `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{16}
}

func (x *ClearResponse) GetCleared() int32 {
	if x != nil {
		return x.Cleared
	}
	return 0
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPrefixes  []string               `protobuf:"bytes,1,rep,name=path_prefixes,json=pathPrefixes,proto3" json:"path_prefixes,omitempty"` // Watch paths starting with these
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRequest) GetPathPrefixes() []string {
	if x != nil {
		return x.PathPrefixes
	}
	return nil
}

type InvalidationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "modified", "deleted", "evicted", "manual"
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidationEvent) Reset() {
	*x = InvalidationEvent{}
	mi := &file_api_proto_cache_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidationEvent) ProtoMessage() {}

func (x *InvalidationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidationEvent.ProtoReflect.Descriptor instead.
func (*InvalidationEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{18}
}

func (x *InvalidationEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvalidationEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InvalidationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_cache_proto protoreflect.FileDescriptor

const file_api_proto_cache_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/cache.proto\x12\x0fcortex.cache.v1\"\xc5\x01\n" +
	"\n" +
	"CacheEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vaccessed_at\x18\x06 \x01(\x03R\n" +
	"accessedAt\x12\x1b\n" +
	"\thit_count\x18\a \x01(\x05R\bhitCount\"G\n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x0evalidate_mtime\x18\x02 \x01(\bR\rvalidateMtime\"l\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x121\n" +
	"\x05entry\x18\x02 \x01(\v2\x1b.cortex.cache.v1.CacheEntryR\x05entry\x12\x14\n" +
	"\x05stale\x18\x03 \x01(\bR\x05stale\"\x85\x01\n" +
	"\n" +
	"SetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x05R\n" +
	"ttlSeconds\"W\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aevicted\x18\x02 \x01(\bR\aevicted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"'\n" +
	"\x11InvalidateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"*\n" +
	"\x12InvalidateResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\"N\n" +
	"\x0fBatchGetRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12%\n" +
	"\x0evalidate_mtime\x18\x02 \x01(\bR\rvalidateMtime\"\xcd\x01\n" +
	"\x10BatchGetResponse\x12H\n" +
	"\aentries\x18\x01 \x03(\v2..cortex.cache.v1.BatchGetResponse.EntriesEntryR\aentries\x12\x16\n" +
	"\x06misses\x18\x02 \x03(\tR\x06misses\x1aW\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.cortex.cache.v1.CacheEntryR\x05value:\x028\x01\"H\n" +
	"\x0fBatchSetRequest\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.cortex.cache.v1.SetRequestR\aentries\"p\n" +
	"\x10BatchSetResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\x05R\n" +
	"errorCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x0e\n" +
	"\fStatsRequest\"\xb1\x02\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12(\n" +
	"\x10total_size_bytes\x18\x02 \x01(\x03R\x0etotalSizeBytes\x12\x1f\n" +
	"\vmax_entries\x18\x03 \x01(\x03R\n" +
	"maxEntries\x12$\n" +
	"\x0emax_size_bytes\x18\x04 \x01(\x03R\fmaxSizeBytes\x12\x12\n" +
	"\x04hits\x18\x05 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x06 \x01(\x03R\x06misses\x12\x1c\n" +
	"\tevictions\x18\a \x01(\x03R\tevictions\x12\x19\n" +
	"\bhit_rate\x18\b \x01(\x01R\ahitRate\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\"h\n" +
	"\x0fPreCacheRequest\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\tR\tdirectory\x12\x1b\n" +
	"\tmax_files\x18\x03 \x01(\x05R\bmaxFiles\"r\n" +
	"\x10PreCacheResponse\x12\x16\n" +
	"\x06cached\x18\x01 \x01(\x05R\x06cached\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\x12\x14\n" +
	"\x05files\x18\x04 \x03(\tR\x05files\"\x0e\n" +
	"\fClearRequest\")\n" +
	"\rClearResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\x05R\acleared\"3\n" +
	"\fWatchRequest\x12#\n" +
	"\rpath_prefixes\x18\x01 \x03(\tR\fpathPrefixes\"]\n" +
	"\x11InvalidationEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xca\x05\n" +
	"\fCacheService\x12@\n" +
	"\x03Get\x12\x1b.cortex.cache.v1.GetRequest\x1a\x1c.cortex.cache.v1.GetResponse\x12@\n" +
	"\x03Set\x12\x1b.cortex.cache.v1.SetRequest\x1a\x1c.cortex.cache.v1.SetResponse\x12U\n" +
	"\n" +
	"Invalidate\x12\".cortex.cache.v1.InvalidateRequest\x1a#.cortex.cache.v1.InvalidateResponse\x12O\n" +
	"\bBatchGet\x12 .cortex.cache.v1.BatchGetRequest\x1a!.cortex.cache.v1.BatchGetResponse\x12O\n" +
	"\bBatchSet\x12 .cortex.cache.v1.BatchSetRequest\x1a!.cortex.cache.v1.BatchSetResponse\x12I\n" +
	"\bGetStats\x12\x1d.cortex.cache.v1.StatsRequest\x1a\x1e.cortex.cache.v1.StatsResponse\x12O\n" +
	"\bPreCache\x12 .cortex.cache.v1.PreCacheRequest\x1a!.cortex.cache.v1.PreCacheResponse\x12F\n" +
	"\x05Clear\x12\x1d.cortex.cache.v1.ClearRequest\x1a\x1e.cortex.cache.v1.ClearResponse\x12Y\n" +
	"\x12WatchInvalidations\x12\x1d.cortex.cache.v1.WatchRequest\x1a\".cortex.cache.v1.InvalidationEvent0\x01B5Z3github.com/cortex/cortex-services/api/proto/cachepbb\x06proto3"

var (
	file_api_proto_cache_proto_rawDescOnce sync.Once
	file_api_proto_cache_proto_rawDescData []byte
)

func file_api_proto_cache_proto_rawDescGZIP() []byte {
	file_api_proto_cache_proto_rawDescOnce.Do(func() {
		file_api_proto_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cache_proto_rawDesc), len(file_api_proto_cache_proto_rawDesc)))
	})
	return file_api_proto_cache_proto_rawDescData
}

var file_api_proto_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_cache_proto_goTypes = []any{
	(*CacheEntry)(nil),         // 0: cortex.cache.v1.CacheEntry
	(*GetRequest)(nil),         // 1: cortex.cache.v1.GetRequest
	(*GetResponse)(nil),        // 2: cortex.cache.v1.GetResponse
	(*SetRequest)(nil),         // 3: cortex.cache.v1.SetRequest
	(*SetResponse)(nil),        // 4: cortex.cache.v1.SetResponse
	(*InvalidateRequest)(nil),  // 5: cortex.cache.v1.InvalidateRequest
	(*InvalidateResponse)(nil), // 6: cortex.cache.v1.InvalidateResponse
	(*BatchGetRequest)(nil),    // 7: cortex.cache.v1.BatchGetRequest
	(*BatchGetResponse)(nil),   // 8: cortex.cache.v1.BatchGetResponse
	(*BatchSetRequest)(nil),    // 9: cortex.cache.v1.BatchSetRequest
	(*BatchSetResponse)(nil),   // 10: cortex.cache.v1.BatchSetResponse
	(*StatsRequest)(nil),       // 11: cortex.cache.v1.StatsRequest
	(*StatsResponse)(nil),      // 12: cortex.cache.v1.StatsResponse
	(*PreCacheRequest)(nil),    // 13: cortex.cache.v1.PreCacheRequest
	(*PreCacheResponse)(nil),   // 14: cortex.cache.v1.PreCacheResponse
	(*ClearRequest)(nil),       // 15: cortex.cache.v1.ClearRequest
	(*ClearResponse)(nil),      // 16: cortex.cache.v1.ClearResponse
	(*WatchRequest)(nil),       // 17: cortex.cache.v1.WatchRequest
	(*InvalidationEvent)(nil),  // 18: cortex.cache.v1.InvalidationEvent
	nil,                        // 19: cortex.cache.v1.BatchGetResponse.EntriesEntry
}
var file_api_proto_cache_proto_depIdxs = []int32{
	0,  // 0: cortex.cache.v1.GetResponse.entry:type_name -> cortex.cache.v1.CacheEntry
	19, // 1: cortex.cache.v1.BatchGetResponse.entries:type_name -> cortex.cache.v1.BatchGetResponse.EntriesEntry
	3,  // 2: cortex.cache.v1.BatchSetRequest.entries:type_name -> cortex.cache.v1.SetRequest
	0,  // 3: cortex.cache.v1.BatchGetResponse.EntriesEntry.value:type_name -> cortex.cache.v1.CacheEntry
	1,  // 4: cortex.cache.v1.CacheService.Get:input_type -> cortex.cache.v1.GetRequest
	3,  // 5: cortex.cache.v1.CacheService.Set:input_type -> cortex.cache.v1.SetRequest
	5,  // 6: cortex.cache.v1.CacheService.Invalidate:input_type -> cortex.cache.v1.InvalidateRequest
	7,  // 7: cortex.cache.v1.CacheService.BatchGet:input_type -> cortex.cache.v1.BatchGetRequest
	9,  // 8: cortex.cache.v1.CacheService.BatchSet:input_type -> cortex.cache.v1.BatchSetRequest
	11, // 9: cortex.cache.v1.CacheService.GetStats:input_type -> cortex.cache.v1.StatsRequest
	13, // 10: cortex.cache.v1.CacheService.PreCache:input_type -> cortex.cache.v1.PreCacheRequest
	15, // 11: cortex.cache.v1.CacheService.Clear:input_type -> cortex.cache.v1.ClearRequest
	17, // 12: cortex.cache.v1.CacheService.WatchInvalidations:input_type -> cortex.cache.v1.WatchRequest
	2,  // 13: cortex.cache.v1.CacheService.Get:output_type -> cortex.cache.v1.GetResponse
	4,  // 14: cortex.cache.v1.CacheService.Set:output_type -> cortex.cache.v1.SetResponse
	6,  // 15: cortex.cache.v1.CacheService.Invalidate:output_type -> cortex.cache.v1.InvalidateResponse
	8,  // 16: cortex.cache.v1.CacheService.BatchGet:output_type -> cortex.cache.v1.BatchGetResponse
	10, // 17: cortex.cache.v1.CacheService.BatchSet:output_type -> cortex.cache.v1.BatchSetResponse
	12, // 18: cortex.cache.v1.CacheService.GetStats:output_type -> cortex.cache.v1.StatsResponse
	14, // 19: cortex.cache.v1.CacheService.PreCache:output_type -> cortex.cache.v1.PreCacheResponse
	16, // 20: cortex.cache.v1.CacheService.Clear:output_type -> cortex.cache.v1.ClearResponse
	18, // 21: cortex.cache.v1.CacheService.WatchInvalidations:output_type -> cortex.cache.v1.InvalidationEvent
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_cache_proto_init() }
func file_api_proto_cache_proto_init() {
	if File_api_proto_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cache_proto_rawDesc), len(file_api_proto_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cache_proto_goTypes,
		DependencyIndexes: file_api_proto_cache_proto_depIdxs,
		MessageInfos:      file_api_proto_cache_proto_msgTypes,
	}.Build()
	File_api_proto_cache_proto = out.File
	file_api_proto_cache_proto_goTypes = nil
	file_api_proto_cache_proto_depIdxs = nil
}
